# Generated by Django 5.1.1 on 2024-09-17 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_doctor_inventoryitem_patient_staff_medicalrecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_quantity', models.IntegerField()),
                ('date_used', models.DateTimeField(auto_now_add=True)),
                ('purpose', models.CharField(max_length=255)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.inventoryitem')),
            ],
        ),
    ]
