# Generated by Django 5.1.1 on 2024-09-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_receiptionist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptionist',
            name='contact_number',
            field=models.IntegerField(),
        ),
    ]
