# Generated by Django 5.1.1 on 2024-09-25 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_receiptionist_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=300)),
                ('contact_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Receiptionist',
        ),
    ]
